run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gofmt
    - goimports
    - misspell
    - revive
    - gocritic
    - gosec
    - unparam
    - gocyclo

linters-settings:
  gocyclo:
    min-complexity: 15

issues:
  exclude-dirs:
    - vendor
